# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aaee697d454e9d7efe439c12f8e8972c5d7566941f9f73ccfc10a7c83021f65c07c8f462dbd7d0699084f1431abe93ebae40df0fa998a2d77ad879bbd9aab31

test:
  secret_key_base: 6022a493907876e25b99bdc07afec4b7f738b332e11a6c090f1fea9da4afbeb9148dba1dd1cb0cc7c1ca54f8e3701a3ac97bed61e8a8dc6d645820e4c163d699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
